
* Introduction

This package extends [[https://github.com/localauthor/][`zk` and `zk-index`]] to include support for working with
files assigned Luhmann-style IDs.

A demo of this package can be viewed here: https://youtu.be/O6iSV4pQQ5g

Currently this package defines Luhmann-style IDs as alphanumeric sequences
between curly braces. They look like this: {1,1,b,3 }

Note the space after the final character. This is necessary for proper
sorting.

The ID is part of the file-name, positioned between the zk-id and the
title.

Because all files with Luhmann-IDs have normal zk-ids, they are normal
zk-files. This naming and ID scheme therefore simply offers a different
organizing scheme within a zk. It is both fully integrated with zk while
being, nevertheless, completely distinct --- a system within a system.


* Add keybindings to zk-index-map

To add these functions to =zk-index-map=, include the following to your
config file, substituting whatever keybindings you like:

#+begin_src emacs-lisp
(define-key zk-index-map (kbd "L") #'zk-luhmann-index-sort)
(define-key zk-index-map (kbd "l") #'zk-luhmann-index)
(define-key zk-index-map (kbd "C-f") #'zk-luhmann-index-forward)
(define-key zk-index-map (kbd "C-b") #'zk-luhmann-index-back)
(define-key zk-index-map (kbd "C-t") #'zk-luhmann-index-unfold)
(define-key zk-index-map (kbd "t") #'zk-luhmann-index-top)
(define-key zk-index-map (kbd "1") #'zk-luhmann-index-level)
(define-key zk-index-map (kbd "2") #'zk-luhmann-index-level)
(define-key zk-index-map (kbd "3") #'zk-luhmann-index-level)
(define-key zk-index-map (kbd "4") #'zk-luhmann-index-level)
(define-key zk-index-map (kbd "5") #'zk-luhmann-index-level)
(define-key zk-index-map (kbd "6") #'zk-luhmann-index-level)
(define-key zk-index-map (kbd "7") #'zk-luhmann-index-level)
(define-key zk-index-map (kbd "8") #'zk-luhmann-index-level)
(define-key zk-index-map (kbd "9") #'zk-luhmann-index-level)
#+end_src

Or, with use-package:

#+begin_src emacs-lisp
(use-package zk-luhmann
  :bind (:map zk-index-map
              ("L" . zk-luhmann-index-sort)
              ("l" . zk-luhmann-index)
              ("C-f" . zk-luhmann-index-forward)
              ("C-b" . zk-luhmann-index-back)
              ("C-t" . zk-luhmann-index-unfold)
              ("t" . zk-luhmann-index-top)
              ("1" . zk-luhmann-index-level)
              ("2" . zk-luhmann-index-level)
              ("3" . zk-luhmann-index-level)
              ("4" . zk-luhmann-index-level)
              ("5" . zk-luhmann-index-level)
              ("6" . zk-luhmann-index-level)
              ("7" . zk-luhmann-index-level)
              ("8" . zk-luhmann-index-level)
              ("9" . zk-luhmann-index-level)))
#+end_src


* Completion-at-point

To add completion at point for files with Luhmann-style IDs, evaluate the following:

#+begin_src emacs-lisp
(add-hook 'completion-at-point-functions
          #'zk-luhmann-completion-at-point 'append)
#+end_src

